# Header
menu:
  Home: /
  # Arquivos: /archives
  Amanda: https://github.com/amandafrois
  Danilo: https://github.com/danilosoarescardoso
  Sobre: /about
# rss: /atom.xml

# Content
excerpt_link: leia mais
excerpt_length: 400

# Favicon
# favicon: /favicon.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: false

# Google Analytics
google_analytics:
  enable: true
  acct: "G-EQX0NLXEGD"

# IntenseDebate ID
intensedebate:
  enable: false
  acct: "317a0bde06cb0f2bae041d31fa4d4f1a"